apiVersion: v1
kind: Namespace
metadata:
  name: nm-alta
---
apiVersion: v1
kind: Namespace
metadata:
  name: nm-baja
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-high
  namespace: nm-alta
spec:
  hard:
    pods: "5"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-low
  namespace: nm-baja
spec:
  hard:
    pods: "1"
--------
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: nm-alta
spec:
  containers:
  - name: pod
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: nm-alta
spec:
  containers:
  - name: pod
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: nm-baja
spec:
  containers:
  - name: pod
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]