apiVersion: v1
kind: Namespace
metadata:
  name: nm-alta
---
apiVersion: v1
kind: Namespace
metadata:
  name: nm-baja
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-high
  namespace: nm-alta
spec:
  hard:
    pods: "5"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-low
  namespace: nm-baja
spec:
  hard:
    pods: "1"
