apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: nm-alta
spec:
  containers:
  - name: pod
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: nm-alta
spec:
  containers:
  - name: pod
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: nm-baja
spec:
  containers:
  - name: pod
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]