apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfspvc
spec:
  accessModes:
    - ReadWriteMany  # Acceso de lectura y escritura para múltiples pods
  resources:
    requests:
      storage: 1Gi  # Solicitar 1 GB de almacenamiento
  volumeMode: Filesystem
