apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    app: apache-web
spec:
  containers:
  - name: apache
    image: httpd:latest  # Usamos la imagen oficial httpd
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs  # Directorio donde se montará el volumen NFS
      name: nfs-volume
      subPath: apache
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: nfs-pvc  # PVC que ya has creado para NFS
