apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-web  
spec:
  restartPolicy: Always  
  containers:
    - name: nginx
      image: nginx
      command: ["nginx", "-g", "daemon off;"]  
      volumeMounts:
        - name: nfs-volume
          mountPath: /usr/share/nginx/html
          subPath: nginx
      env:
        - name: SERVER_NAME
          value: "localhost"  
  initContainers:
    - name: nginx-config
      image: busybox
      command:
        - "sh"
        - "-c"
        - |
          # Crear el directorio para la configuración de Nginx
          mkdir -p /etc/nginx/conf.d
          # Agregar configuración personalizada para Nginx
          echo "server { listen 80; server_name localhost; location / { root /usr/share/nginx/html; index index.html; } }" > /etc/nginx/conf.d/default.conf
      volumeMounts:
        - name: nfs-volume
          mountPath: /usr/share/nginx/html
          subPath: nginx
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc
