apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-subdir  # Asegúrate de que esté configurado correctamente
  nfs:
    path: /mnt/nfs_share
    server: 172.25.157.234  # Reemplaza con la IP correcta del servidor NFS
    readOnly: false
