apiVersion: v1
kind: Pod
metadata:
  name: ipfe-pod
  namespace: default
spec:
  containers:
    - name: ipfe
      image: faasioflex/ipython:jogugil
      command: ["/bin/bash", "-c", "
        if ! dpkg -l | grep -q iputils-ping; then
          apt-get update && apt-get install -y iputils-ping;
        fi;
        if ! dpkg -l | grep -q iproute2; then
          apt-get update && apt-get install -y iproute2;
        fi;
        if ! dpkg -l | grep -q net-tools; then
          apt-get update && apt-get install -y net-tools;
        fi;
        if ! dpkg -l | grep -q iputils-tracepath; then
          apt-get update && apt-get install -y iputils-tracepath;
        fi;
        tail -f /dev/null
      "]
      
  tolerations:
    - key: "node.kubernetes.io/not-ready"
      operator: "Exists"
      effect: "NoExecute"
    - key: "node.kubernetes.io/unreachable"
      operator: "Exists"
      effect: "NoExecute"
